### ISSUE TITLE
Not Printing Version Tag

### ISSUE THREAD

**Issue by ghost** [hldr4/shaka-packager#1]
## System info
**Operating System**: All Systems
**Shaka Packager Version**: v3.0.2

## Issue and steps to reproduce the problem

**Packager Command**: 
`shaka-packager --version`

**What is the expected result?**
It should print `{version_tag}-{version_hash}`

**What happens instead?**
Its only printing the `version_hash`

**Comment by hldr4** [comment]
Pushed an attempted fix, have not tested it with a build though. The script responsible for grabbing the version tag does get it now at least so it should work
